### ISSUE TITLE
tls ingress readiness

### ISSUE THREAD

**Issue by y0zg** [dgn/oidc-filter#1]
This is very interesting example and I appreciate if you help me with my questions

After you logged in with keycloak, can you see Authorization Bearer token in the browser or it's a cookie?

I tried to test this example with istio ingress and everything works fine unless I enter keycloak credentials (redirection to keycloak without JWT token works), then I receive 503 istio ingress error for endpoint `/?session_state`

I put keycloak external URLs for all entries(keycloak ingress is configured with tls and works fine) but it didn't help
https://github.com/dgn/oidc-filter/blob/master/example/envoyfilter.yaml#L27-L30

https://github.com/dgn/oidc-filter/blob/master/example/istio-auth.yaml#L11-L12

istio-proxy logs:

```
[Envoy (Epoch 0)] [2020-08-30 22:00:45.712][24][debug][router] [external/envoy/source/common/router/router.cc:474] [C66284][S8249649652266042808] cluster 'outbound|8000||httpbin.default.svc.cluster.local' match for URL '/'
[Envoy (Epoch 0)] [2020-08-30 22:00:45.712][24][debug][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:1230] no healthy host for HTTP connection pool
[Envoy (Epoch 0)] [2020-08-30 22:00:45.712][24][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1422] [C66284][S8249649652266042808] Sending local reply with details no_healthy_upstream
[Envoy (Epoch 0)] [2020-08-30 22:00:45.712][24][debug][filter] [src/envoy/http/mixer/filter.cc:135] Called Mixer::Filter : encodeHeaders 2
[Envoy (Epoch 0)] [2020-08-30 22:00:45.712][24][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1620] [C66284][S8249649652266042808] encoding headers via codec (end_stream=false):
':status', '503'
'content-length', '19'
'content-type', 'text/plain'
'date', 'Sun, 30 Aug 2020 22:00:45 GMT'
'server', 'istio-envoy'
```

From infrastructure side , everything should be configured correctly as I tested the same authentication flow (istio+keycloak) with keycloak gatekeeper/proxy and it works well.

**Comment by dgn** [comment]
Hi @y0zg, make sure to set the correct `auth_cluster` in your filter config. This has to be the cluster name generated by Istio that points to your Keycloak instance. You can see the clusters in your environment by running `istioctl pc clusters <INGRESS_POD_NAME>`

**Comment by y0zg** [comment]
@dgn Thank you for following up

checked both 80 and 8443 ports available in clusters but still the same issue

**Comment by y0zg** [comment]
started working with 80 port! Cool!
