### ISSUE TITLE
What is the proper way to make istio-proxy filesystem non readonly to copy wasm filter

### ISSUE THREAD

**Issue by y0zg** [dgn/oidc-filter#2]
Hi @dgn 

What is the proper way to make istio-proxy filesystem writable in order to copy wasm filter?

Usually you will get this error if you try to copy or create the folder 
```
k exec pod podname -c istio-proxy -- mkdir -p /var/local/lib/wasm-filters/
mkdir: cannot create directory '/var/local/lib': Read-only file system
command terminated with exit code 1
```

**Comment by dgn** [comment]
You can add annotations to add an `emptyDir` volume to the pod and mount it into the proxy container. Take a look at my deployment in the example directory: https://github.com/dgn/oidc-filter/blob/2425a94cbaa78a8fcf29cf30797f55074c59d4b1/example/httpbin.yaml#L51-L52
